### ISSUE TITLE
Help improve this project

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/fluentmail#5]
Hi,

I want to improve this lib, make it more pythonic, flexible, usable and well designed. So I ask to you: 

**What's your idea of a good email library for Python?**

I want to design something as good as [requests](https://github.com/kennethreitz/requests). Requests is an awesome lib to work with HTTP Requests, but there's no such thing to work with SMTP, that's was the point to start this library. Also, there's a similar project called [Sender](http://sender.readthedocs.org/en/latest/).

Feel free to share any ideas, everything is welcome, including pull requests.

**Comment by jhermann** [comment]
As you quoted requests, do what it does and write the index page of the docs, with the *common* examples of use, and make them *easy*. Then implement that, and that only. I call that "documentation driven development" or D³. :smirk:

And it is basically

    from fluentmail import mail
    letter = mail(from=…, to=…, subject=…, body=…, markup="markdown", format="html+text",
             headers={…}, attachments={…})
    letter.send((host, port)) # shortcut for m.send(fluentmail.SMTP(host, port, password=…))

with body taking text + streams, and as you can see an easy way to feed a dual html/text mail. For finer control, accept a dict for body, with html + text keys. `send()` should default to localhost SMTP.

In addition, you might want to add an actual ‘fluent’ interface, i.e. `mail().from(…).to(…)…`.

**Comment by jpscaletti** [comment]
https://github.com/lucuma/MailShake :trollface:

**Comment by jhermann** [comment]
fluentmail tests for Python3, MailShake doesn't though.

**Comment by alexandrevicenzi** [comment]
@jhermann thanks and fluentmail has a fluent api, but I dislike a little bit.

@jpscaletti didn't know about MailShake :no_mouth:, and probably there are others libs to send email.

**Comment by jhermann** [comment]
BTW, I see the mixing of transport (SMTP) and mail entity as a smell. The email object should just have a shallow delegating send method…

    def send(self, mta=None, **kwargs):
        mta = mta or default_mta
        return mta.send(self, **kwargs)

**Comment by alexandrevicenzi** [comment]
Let's focus, I don't want to tell what's better or who has a better lib, I just want a good design for and email api. If there's one that already match this pattern, ok, but if not, others can use a well design pattern to build a custom lib. 

It's like all Python web frameworks. They look almost the same, but have good and bad points each.
