### ISSUE TITLE
Submodule `backends` not included during install

### ISSUE THREAD

**Issue by geudrik** [alexandrevicenzi/fluentmail#7]
https://github.com/alexandrevicenzi/fluentmail/blob/master/setup.py#L13

Currently, the setup script doesn't copy the backends submodule you have, completely preventing your library from installing (also, your latest PyPi is from 2014, so that's no bueno)

Change to read `packages=['fluentmail', 'fluentmail.backends'],` or use the setuptools helper `packages = find_packages(".")`

**Comment by alexandrevicenzi** [comment]
Fixed by #8.
